blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/hex-digital/captaincss/issues/new
    about: 'Suggest any ideas you have using our issues.'
  - name: Help
    url: https://github.com/hex-digital/captaincss/issues/new
    about: 'If you have a question or need help, ask a question in issues.'
  - name: Documentation Issue
    url: https://github.com/hex-digital/captaincss-docs
    about: 'For documentation issues, suggest changes on our documentation repository.'
